# Generated by Django 5.2.11 on 2026-02-19 07:06

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_voice_id",
                    models.CharField(default="af_bella", max_length=100),
                ),
                ("tts_speed", models.FloatField(default=1.0)),
                ("zoom_intensity", models.FloatField(default=1.3)),
                (
                    "subtitle_font",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("subtitle_color", models.CharField(default="#FFFFFF", max_length=7)),
            ],
            options={
                "verbose_name": "Global Settings",
                "verbose_name_plural": "Global Settings",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("resolution_width", models.IntegerField(default=1920)),
                ("resolution_height", models.IntegerField(default=1080)),
                ("framerate", models.IntegerField(default=30)),
                (
                    "output_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence_index", models.IntegerField(default=0)),
                ("text_content", models.TextField(blank=True, default="")),
                ("image_prompt", models.TextField(blank=True, default="")),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.segment_image_path
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to=api.models.segment_audio_path
                    ),
                ),
                ("audio_duration", models.FloatField(blank=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_index"],
            },
        ),
    ]
