# Generated by Django 5.2.11 on 2026-02-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="custom_font_file",
            field=models.FileField(blank=True, null=True, upload_to="fonts/"),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="ken_burns_zoom",
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="render_fps",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="render_height",
            field=models.PositiveIntegerField(default=1080),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="render_width",
            field=models.PositiveIntegerField(default=1920),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="subtitle_font_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="subtitle_font_family",
            field=models.CharField(default="Arial", max_length=200),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="subtitle_font_size",
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="subtitle_position",
            field=models.CharField(
                choices=[("bottom", "Bottom"), ("center", "Center"), ("top", "Top")],
                default="bottom",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="transition_duration",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
