# Generated by Django 5.2.11 on 2026-02-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_globalsettings_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="inter_segment_silence",
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="subtitles_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
