# Generated by Django 5.2.11 on 2026-02-24 02:04

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_inter_segment_silence_and_subtitles_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.ImageField(upload_to=api.models.logo_upload_path)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="logo_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="logo_margin",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="logo_opacity",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="logo_position",
            field=models.CharField(
                choices=[
                    ("top-left", "Top Left"),
                    ("top-right", "Top Right"),
                    ("bottom-left", "Bottom Left"),
                    ("bottom-right", "Bottom Right"),
                ],
                default="bottom-right",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="logo_scale",
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="active_logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_in_settings",
                to="api.logo",
            ),
        ),
    ]
