# Generated by Django 5.2.11 on 2026-02-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_logo_globalsettings_logo_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="subtitle_y_position",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
