# Generated by Django 5.2.11 on 2026-02-25 08:46

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_globalsettings_subtitle_y_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutroVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(upload_to=api.models.outro_video_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="outro_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="active_outro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_in_settings",
                to="api.outrovideo",
            ),
        ),
    ]
