# Generated by Django 5.2.11 on 2026-02-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_outrovideo_globalsettings_outro_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="active_logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_using",
                to="api.logo",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="active_outro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_using",
                to="api.outrovideo",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="custom_font_file",
            field=models.FileField(blank=True, null=True, upload_to="fonts/"),
        ),
        migrations.AddField(
            model_name="project",
            name="default_voice_id",
            field=models.CharField(default="af_bella", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="inter_segment_silence",
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name="project",
            name="ken_burns_zoom",
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name="project",
            name="logo_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="logo_margin",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="project",
            name="logo_opacity",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="project",
            name="logo_position",
            field=models.CharField(
                choices=[
                    ("top-left", "Top Left"),
                    ("top-right", "Top Right"),
                    ("bottom-left", "Bottom Left"),
                    ("bottom-right", "Bottom Right"),
                ],
                default="bottom-right",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="logo_scale",
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name="project",
            name="outro_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle_font",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle_font_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle_font_family",
            field=models.CharField(default="Arial", max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle_font_size",
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle_position",
            field=models.CharField(
                choices=[("bottom", "Bottom"), ("center", "Center"), ("top", "Top")],
                default="bottom",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle_y_position",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitles_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="transition_duration",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="project",
            name="tts_speed",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="project",
            name="zoom_intensity",
            field=models.FloatField(default=1.3),
        ),
    ]
